### PR TITLE
Support for other languages

### PR DESCRIPTION
**Pull request by nknapp**
This is a pull-request for issue #1.
I've added an options parameter to the extract-function. This parameter is an object that can have a `filename`-property. If no filename is set, `abc.js` will be assumed to cover backwards compatibility.
I've used the `comment-patterns` module to determine the comment-patterns for the programming language determined by the filename.
Tests are green, including my new test-case for a Handlebars-file,  and I have included a small example in the `.verb.md` template (but not in the README).

I have not tested any other languages than JavaScript and Handlebars.

I have not grasped `Extracting from files`-example in the readme yet. Otherwise I would have adapted it as well.

Finally, I guess having three commits for this issue is not nice as well, so if you comment on my commits, I will combine these three with additional changes to be made and resubmit a pull-request containing just one commit.
Also I would publish `comment-patterns` as version 1.0.0.
It would be nice if you had a look.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
haven't had a chance to review the pr in detail yet, just wanted to say thanks and let you know I didn't forget!

**Comment by jonschlinkert** [comment]
also about the optimization stuff you mentioned, think we can try to do that before merging (if you haven't)?  one of the goals of this project is to be fast. fwiw, I also have a lib that extracts comments with esprima, but it's much slower so I always use this one. 

Another thing we can do to ensure that the lookups only happen once, regardless of how you're looping, is to catch the results on the first lookup.

``` js
var cache = {};

function foo(lang) {
  return cache[lang] || (cache[lang] = lookup(lang));
}
```

**Comment by nknapp** [comment]
I've added pre-compiled indexes "nameMatcher"-> "index within the database-array" to the project. The files are not in the repository, but generated on prepublish and maintained in one js-file per language.

Lookup of a language (for a .js-file) is now equivalent to `base[byMatcher['.js']]`

**Comment by nknapp** [comment]
The more I think about it... I think I can come up with a better solution to incorporate `comment-patterns` into `extract-comments`.

**Comment by nknapp** [comment]
I would consider this pull-request obsolete. I'll make a new one for discussion of a slightly different approach

**Pull request closed without merging**
